version: '3.1'
services:
  web:
    build: .
    ports:
      - "3000:3000"
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/app

volumes:
    db: